### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by RobotsAreCrazy** [Sylensky/poe-hat-b#2]
I have a garbled oled display so thinking I need to fresh install it, so would I go about uninstalling it?

Thanks

**Comment by Sylensky** [comment]
Since the current state of this small tool is not the brightest this can definetly be improved...

However for now you can uninstall the python package with `pip uninstall poe-hat-b`.
After that you have to 
1. `systemctl stop poe-hat.service`
2. `systemctl disable poe-hat.service`
3. `rm /etc/systemd/system/poe-hat.service`
3. `rm /usr/lib/systemd/system/poe-hat.service`

**Comment by RobotsAreCrazy** [comment]
hadmin@pi-srv:/usr/share/poe-hat $ ./install.sh
Hit:1 http://ukdebian.mirror.anlx.net/debian bookworm InRelease
Hit:2 http://debian.proxad.net/debian bookworm InRelease
Hit:3 http://ftp.uk.debian.org/debian bookworm InRelease
Hit:4 http://security.debian.org/debian-security bookworm-security InRelease
Hit:5 http://deb.debian.org/debian bookworm InRelease
Hit:6 http://ftp.is.debian.org/debian bookworm InRelease
Hit:7 http://deb.debian.org/debian bookworm-updates InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (22.3.1+dfsg-1).
python3-pil is already the newest version (9.4.0-1+b1).
python3-smbus is already the newest version (4.3-2+b2).
libatlas-base-dev is already the newest version (3.10.3-13).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Defaulting to user installation because normal site-packages is not writeable
Processing /usr/share/poe-hat
  Preparing metadata (setup.py) ... done
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from poe-hat-b==0.1.1) (0.7.1a4)
Requirement already satisfied: numpy in /home/bhadmin/.local/lib/python3.10/site-packages (from poe-hat-b==0.1.1) (1.24.1)
Requirement already satisfied: smbus2 in /home/bhadmin/.local/lib/python3.10/site-packages (from poe-hat-b==0.1.1) (0.4.2)
Building wheels for collected packages: poe-hat-b
  Building wheel for poe-hat-b (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      error: could not create 'build': Permission denied
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with
pip.
  ERROR: Failed building wheel for poe-hat-b
  Running setup.py clean for poe-hat-b
Failed to build poe-hat-b
Installing collected packages: poe-hat-b
  Running setup.py install for poe-hat-b ... error
  error: subprocess-exited-with-error
  × Running setup.py install for poe-hat-b did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      error: could not create 'build': Permission denied
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with
pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> poe-hat-b
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
● poe-hat.service - Waveshare Poe Hat B
     Loaded: loaded (/etc/systemd/system/poe-hat.service; enabled; preset: enabled)
     Active: active (running) since Tue 2023-01-17 18:22:51 GMT; 55ms ago
   Main PID: 7730 (python3)
      Tasks: 1 (limit: 8985)
        CPU: 48ms
     CGroup: /system.slice/poe-hat.service
             └─7730 python3 usr/share/poe-hat/main.py
Jan 17 18:22:51 pi-srv systemd[1]: Started Waveshare Poe Hat B.
bhadmin@pi-srv:/usr/share/poe-hat $

**Comment by RobotsAreCrazy** [comment]
Only difference is have not ran as sudo
On pi os bookworm sourcelist

**Comment by RobotsAreCrazy** [comment]
received error: "WARNING: Skipping poe-hat-b as it is not installed."

**Comment by Sylensky** [comment]
`received error: "WARNING: Skipping poe-hat-b as it is not installed."`
Where does this occur?

Ah you try to install it `non system-wide` which i didn't consider.. Run it with `sudo` to have it globally installed as you shouldn't need to touch it anymore after installing.

**Comment by RobotsAreCrazy** [comment]
That error was when doing sudo pip uninstall poe-hat, I have modified the install.sh with the change of dependency with python3-smbus2. I will report back if successful.

I had ran the ./install.sh without sudo this time due to pip stating running as root warning, so I thought I'd see if it would work.

One other question will I need to create a crontab that runs main.py at reboot etc?

Thankyou so much for your help I really appreciate it.

**Comment by RobotsAreCrazy** [comment]
bhadmin@pi-srv:/usr/share/poe-hat $ sudo ./install.sh
Hit:1 http://ukdebian.mirror.anlx.net/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease
Hit:3 http://ftp.uk.debian.org/debian bookworm InRelease
Hit:4 http://debian.proxad.net/debian bookworm InRelease
Hit:5 http://deb.debian.org/debian bookworm-updates InRelease
Hit:6 http://ftp.is.debian.org/debian bookworm InRelease
Hit:7 http://security.debian.org/debian-security bookworm-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (22.3.1+dfsg-1).
python3-pil is already the newest version (9.4.0-1+b1).
libatlas-base-dev is already the newest version (3.10.3-13).
The following NEW packages will be installed:
  python3-smbus2
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 11.8 kB of archives.
After this operation, 57.3 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main arm64 python3-smbus2 arm64 0.4.2-1 [11.8 kB]
Fetched 11.8 kB in 0s (96.7 kB/s)
Selecting previously unselected package python3-smbus2.
(Reading database ... 43150 files and directories currently installed.)
Preparing to unpack .../python3-smbus2_0.4.2-1_arm64.deb ...
Unpacking python3-smbus2 (0.4.2-1) ...
Setting up python3-smbus2 (0.4.2-1) ...
Processing /usr/share/poe-hat
  Preparing metadata (setup.py) ... done
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from poe-hat-b==0.1.1) (0.7.1a4)
Collecting numpy
  Downloading numpy-1.24.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 7.2 MB/s eta 0:00:00
Requirement already satisfied: smbus2 in /usr/lib/python3/dist-packages (from poe-hat-b==0.1.1) (0.4.2)
Building wheels for collected packages: poe-hat-b
  Building wheel for poe-hat-b (setup.py) ... done
  Created wheel for poe-hat-b: filename=poe_hat_b-0.1.1-py3-none-any.whl size=6716780 sha256=88c7102f20beb6219bfa0bd501999b0ac1450e92f056b177fca9092f1160ffa4
  Stored in directory: /root/.cache/pip/wheels/d0/21/51/c67a9ba63c17800011293583b989447b52880fdea965803915
Successfully built poe-hat-b
Installing collected packages: numpy, poe-hat-b
Successfully installed numpy-1.24.1 poe-hat-b-0.1.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Created symlink /etc/systemd/system/multi-user.target.wants/poe-hat.service → /etc/systemd/system/poe-hat.service.
● poe-hat.service - Waveshare Poe Hat B
     Loaded: loaded (/etc/systemd/system/poe-hat.service; enabled; preset: enabled)
     Active: active (running) since Tue 2023-01-17 23:06:57 GMT; 41ms ago
   Main PID: 2700 (python3)
      Tasks: 1 (limit: 8985)
        CPU: 34ms
     CGroup: /system.slice/poe-hat.service
             └─2700 python3 usr/share/poe-hat/main.py
Jan 17 23:06:57 pi-srv systemd[1]: Started Waveshare Poe Hat B.
bhadmin@pi-srv:/usr/share/poe-hat $

**Comment by RobotsAreCrazy** [comment]
Looks like it went through fine, I am wondering what caused garbled text last time I installed this....

![Screenshot_20230117_231329.jpg](https://user-images.githubusercontent.com/9435484/213032853-bde01475-6001-4641-a46c-8b290998cf33.jpg)

**Comment by Sylensky** [comment]
no need to create a cron job for the hat. `systemd` takes care of it since the `poe-hat.service` starts automatically. 
Essentially written here:
`● poe-hat.service - Waveshare Poe Hat B
Loaded: loaded (/etc/systemd/system/poe-hat.service; enabled; preset: enabled)`

**Comment by RobotsAreCrazy** [comment]
Was weird as last time I installed it,on reboot it never started, so that's why I was asking....are you planning anymore changes to the script like maybe system memory usage might be useful?

**Comment by RobotsAreCrazy** [comment]
Thankyou for making this script available, really thankful for it and your help with getting it running, now I need to try and get blinkt cputemp working to show leds depending on CPU temp level

**Comment by Sylensky** [comment]
The script wasn't being tested as of the usage of the hat and this code is a little bit different. Just wanted to have it usable for other approaches aswell. 
Noticed anything wierd upon restart?

**Comment by RobotsAreCrazy** [comment]
On reboot, the display is still active..I will completely kill power to it that is the real test.

On power kill and powered on,  it displays correctly when it boots back up.

I'm going to image the drive I know how finicky this can be, so I want a working baseline image with things working at this point.

Can memory usage be added?

**Comment by Sylensky** [comment]
Ok then this can be considered resolve.d
